name: Build en Deploy React App to UGent file share

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        echo "Installing dependencies..."
        npm install
      working-directory: C:\Users\robbe\OneDrive\Documenten\Persoonlijke projecten\personal-website

    - name: Build React app
      run: |
        echo "Building React app..."
        npm run build
      working-directory: C:\Users\robbe\OneDrive\Documenten\Persoonlijke projecten\personal-website

    - name: Copy build to target directory
      run: |
        echo "Copying build files to target directory..."
        cp -r build/* W:\users
      working-directory: C:\Users\robbe\OneDrive\Documenten\Persoonlijke projecten\personal-website
