name: Build en Deploy React App to UGent file share

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: npm install
      working-directory: C:\Users\robbe\OneDrive\Documenten\Persoonlijke projecten\personal-website

    - name: Build React app
      run: npm run build
      working-directory: C:\Users\robbe\OneDrive\Documenten\Persoonlijke projecten\personal-website

    - name: Copy build to target directory
      run: cp -r -Force build/* W:\users
      working-directory: C:\Users\robbe\OneDrive\Documenten\Persoonlijke projecten\personal-website
